### ISSUE TITLE
Code review 1

### ISSUE THREAD

**Issue by alafuzof** [tulir/fifteen#1]
Repository cloned 2019-02-15 13:55, commit ...281ec5

I would like to preface my comments by noting that I've never coded in Go, so I 
may have misunderstood some of the code. Caveat emptor!

As given the build instructions do not produce an executable on my machine,
since the build command tries to produce an executable named 'fifteen', but
this name conflicts with the source directory name. I was able to circumvent
this by creating a build directory and/or by using the -o switch to rename
the target executable.

Overall, the code is nicely structured. Some functions could use a little more
documentation to make what's being done more apparent (e.g. Solvable(), I only
have a vague idea of what is being done there after looking into 15 puzzle 
solvability), but all the functions have a brief descriptions, good job!

The animated UI is a cool idea, even if it isn't central in terms of course
content. However, during my testing I was unable to get it to show the solver
taking steps (it only seems to show the first and last state). The UI code is 
predictably complicated, and it's the part I spent the least time reviewing, so
it could be that I was just using the wrong flags or something.

The division of labor between the Position data structure and Puzzle is a bit
counter-intuitive in my opinion. In particular, I think the move validity is
probably something I would do in the Puzzle class, since in it will also depend
on the position of the blank (see also bug 2 below). 
 
I found a couple bugs in the code:

1) In the NewSolvedPuzzle function, the position of the blank is always set to 
(X,Y)=(4,4), which may be outside the data array (3x3 puzzles) or occupied by a 
non-blank, when the puzzle size is greater than 4x4. This will also lead to 
strange results with Move(), because the function will move the false blank
around. As I understand it, the following test should not fail (but does!):

```golang
func TestPuzzle_BlankValue(t *testing.T) {
	for i := 3; i<16; i++ {
		puzzle, _ := NewSolvedPuzzle(i)
		assert.Equal(t, 0, puzzle.Get(puzzle.blank.X, puzzle.blank.Y));
	}
}
```

2) This is not necessarily a problem, since the Move() method is only called by
your own code and not "user-facing", but I think it might be worth checking if
a move is "game valid" (i.e. next to the blank) in the Move() method. Checking
for this could catch hidden bugs in other parts of the code.

3) The Parser class could use a little more checking. The parser does not check
for repeated numbers or blanks, or for the existence of a blank. Also, the blank
position is not set. In particular the following tests should not fail (there
should also be a test for checking that the blank position is set correctly):

```golang
func TestParsePuzzle_RepeatedValue(t *testing.T) {
	puzzle, err := ParsePuzzle(
		"1 1 1\n" +
		"1 1 1\n" +
		"1 1 1")
	assert.Error(t, err)
	assert.Nil(t, puzzle)
}

func TestParsePuzzle_MultipleBlanks(t *testing.T) {
	puzzle, err := ParsePuzzle(
		"- 2 3\n" +
		"4 5 6\n" +
		"7 8 -")
	assert.Error(t, err)
	assert.Nil(t, puzzle)
}
```

**Comment by tulir** [comment]
Thanks for the review!

I implemented/fixed most of the ideas/problems:
* Fixed the build instructions
* Included all of your tests
* Made the parser check validity and set the blank position
* Fixed the blank position in NewSolvedPuzzle
* Moved getting valid moves to `Puzzle`
* Added move validation to `Move()`

> during my testing I was unable to get it to show the solver taking steps (it only seems to show the first and last state).

This might be caused by the puzzle being too easy to solve (e.g. number of shuffle moves under 50). The step animation doesn't have any sleeps while it's solving, so if solving only takes a very short time, it won't have time to render anything.

The algorithm step animation also turned out to be pretty un-interesting: it doesn't make any cool patterns and it can't have artificial delays because that would make solving really slow.

> commit ...281ec5

btw: GitHub will automatically linkify commit hashes if you just paste the full hash. For example, `249f66f6d0dcf86bcde93983126109d1bc281ec5` turns into 249f66f6d0dcf86bcde93983126109d1bc281ec5
